### PR TITLE
Set response field on request failure

### PR DESCRIPTION
**Pull request by dmason30**
Fixes https://github.com/spatie/laravel-webhook-client/issues/19

(Sorry I created the original issue on the wrong repository 🤣 ).

The new response properties in PR #14 should also be added to the new section added here.

### CODE REVIEW

**Comment by freekmurze** [comment]
This seems good, but I don't like the fact that we expose a property to show the response. Could you make it private and add a method `getResponse`.

Also add a section to the readme explaining how to get the response.

And after that, it'll be perfect 👍

**Comment by dmason30** [comment]
I am happy to make those changes but  just check with you changing the access for the response property it would be a **breaking change**?

I can see currently in the readme the public property is currently mentioned so chances are it is being used by a decent number of people (including me 😄)

```
response: the response returned by the remote app. Can be an instance of \GuzzleHttp\Psr7\Response or null.
```

Once confirmed it is ok I will get this done as soon as I can.

**Comment by judgej** [comment]
If it's PSR-7, should the response not be `\Psr\Http\Message\ResponseInterface` rather than `\GuzzleHttp\Psr7\Response`? It's a pedantic point, but the whole idea of the PSRs is that they offer interfaces that can have any number of implementations, and people should be hinting against the interfaces and not the implementations.

**Comment by freekmurze** [comment]
Thanks!

**Pull request merged**
